services:
  postgres:
    image: postgres:15
    container_name: user-subscribe-service-db
    restart: always
    environment:
      POSTGRES_DB: user_subscribe_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
